//! Text attributes. Every attribute exists in two forms generated by one macro:
//! a sparse `…Attrs` (all `Option`, used by styles and local overrides) and a complete `…Props`
//! (resolved values used by the composer). Resolution layers sparse attrs over defaults.

use serde::{Deserialize, Serialize};

macro_rules! attr_set {
    (
        $(#[$m:meta])*
        $attrs:ident / $props:ident {
            $( $(#[$fm:meta])* $field:ident : $ty:ty = $default:expr ),* $(,)?
        }
    ) => {
        $(#[$m])*
        #[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
        #[serde(default, rename_all = "camelCase")]
        pub struct $attrs {
            $( $(#[$fm])* #[serde(skip_serializing_if = "Option::is_none")] pub $field: Option<$ty>, )*
        }

        /// Fully resolved values.
        #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
        #[serde(default, rename_all = "camelCase")]
        pub struct $props {
            $( $(#[$fm])* pub $field: $ty, )*
        }

        impl Default for $props {
            fn default() -> Self {
                Self { $( $field: $default, )* }
            }
        }

        impl $attrs {
            /// Overlay `other` on top of `self` (fields set in `other` win).
            pub fn merge(&mut self, other: &$attrs) {
                $( if other.$field.is_some() { self.$field = other.$field.clone(); } )*
            }
            pub fn is_empty(&self) -> bool {
                true $( && self.$field.is_none() )*
            }
            /// Number of fields set (for "+" override indicators).
            pub fn count(&self) -> usize {
                0 $( + self.$field.is_some() as usize )*
            }
            /// Field names that are set (camelCase).
            pub fn keys(&self) -> Vec<&'static str> {
                let mut v = Vec::new();
                $( if self.$field.is_some() { v.push(attr_key(stringify!($field))); } )*
                v
            }
            /// Set one field from JSON by camelCase or snake_case name.
            pub fn set_json(&mut self, key: &str, value: &serde_json::Value) -> Result<(), String> {
                let k: String = key.chars().filter(|c| *c != '_').collect::<String>().to_ascii_lowercase();
                $(
                    if k == stringify!($field).replace('_', "") {
                        if value.is_null() {
                            self.$field = None;
                        } else {
                            self.$field = Some(serde_json::from_value(value.clone()).map_err(|e| format!("{key}: {e}"))?);
                        }
                        return Ok(());
                    }
                )*
                Err(format!("unknown attribute `{key}`"))
            }
            /// Fields where `self` differs from `base`'s resolved value (used for "clear overrides").
            pub fn diff_from(&self, base: &$props) -> $attrs {
                let mut out = $attrs::default();
                $( if let Some(v) = &self.$field { if *v != base.$field { out.$field = Some(v.clone()); } } )*
                out
            }
            /// Names of every attribute.
            pub fn all_keys() -> &'static [&'static str] {
                &[ $( stringify!($field), )* ]
            }
        }

        impl $props {
            pub fn apply(&mut self, a: &$attrs) {
                $( if let Some(v) = &a.$field { self.$field = v.clone(); } )*
            }
            /// The attributes where `self` and `other` differ, with `other`'s values.
            pub fn delta(&self, other: &$props) -> $attrs {
                let mut out = $attrs::default();
                $( if self.$field != other.$field { out.$field = Some(other.$field.clone()); } )*
                out
            }
            /// Keep only values common to all (`None` where they differ) — for mixed selections.
            pub fn common<'a>(items: impl IntoIterator<Item = &'a $props>) -> $attrs {
                let mut it = items.into_iter();
                let Some(first) = it.next() else { return $attrs::default() };
                let mut out = $attrs { $( $field: Some(first.$field.clone()), )* };
                for p in it {
                    $( if out.$field.as_ref().is_some_and(|v| *v != p.$field) { out.$field = None; } )*
                }
                out
            }
        }
    };
}

fn attr_key(snake: &'static str) -> &'static str {
    snake
}

// ---------- value types ----------

#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind", content = "value")]
pub enum Leading {
    /// Auto leading (percentage of the largest size on the line, Justification → Auto Leading).
    #[default]
    Auto,
    Points(f64),
}

/// Paragraph direction.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TextDirection {
    #[default]
    LeftToRight,
    RightToLeft,
}

/// Digits (World-Ready): the figures 0–9 are drawn as these.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Digits {
    /// Contextual digits; composition selects the preceding strong script/language.
    #[default]
    Default,
    /// European (0123).
    Arabic,
    /// Arabic-Indic (٠١٢٣).
    Hindi,
    /// Extended Arabic-Indic, as used for Persian and Urdu (۰۱۲۳).
    Farsi,
    /// Those of the text's language (Thai, Devanagari, Bengali, Arabic, Persian…); else as typed.
    Native,
}

impl Digits {
    /// The digit `c` (0–9) is drawn as, for text in `language`.
    pub fn map(self, c: char, language: &str) -> char {
        let d = match c {
            '0'..='9' => c as u32 - '0' as u32,
            '\u{0660}'..='\u{0669}' => c as u32 - 0x0660,
            '\u{06F0}'..='\u{06F9}' => c as u32 - 0x06F0,
            _ => return c,
        };
        let zero = match self {
            Digits::Default => return c,
            Digits::Arabic => 0x0030,
            Digits::Hindi => 0x0660,
            Digits::Farsi => 0x06F0,
            Digits::Native => {
                let l = language.to_ascii_lowercase();
                match () {
                    _ if l.starts_with("arabic") || l == "ar" || l.starts_with("ar-") => 0x0660,
                    _ if l.starts_with("persian")
                        || l.starts_with("farsi")
                        || l.starts_with("urdu")
                        || l == "fa"
                        || l.starts_with("fa-")
                        || l == "ur"
                        || l.starts_with("ur-") =>
                    {
                        0x06F0
                    }
                    _ if l.starts_with("hindi") || l.starts_with("marathi") || l.starts_with("nepali") || l.starts_with("sanskrit") => 0x0966,
                    _ if l.starts_with("bengali") => 0x09E6,
                    _ if l.starts_with("gujarati") => 0x0AE6,
                    _ if l.starts_with("punjabi") => 0x0A66,
                    _ if l.starts_with("tamil") => 0x0BE6,
                    _ if l.starts_with("telugu") => 0x0C66,
                    _ if l.starts_with("kannada") => 0x0CE6,
                    _ if l.starts_with("malayalam") => 0x0D66,
                    _ if l.starts_with("thai") => 0x0E50,
                    _ if l.starts_with("lao") => 0x0ED0,
                    _ if l.starts_with("tibetan") => 0x0F20,
                    _ if l.starts_with("burmese") => 0x1040,
                    _ if l.starts_with("khmer") => 0x17E0,
                    _ => return c,
                }
            }
        };
        char::from_u32(zero + d).unwrap_or(c)
    }
}

/// A tracked change on text.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ChangeMark {
    #[default]
    None,
    Inserted,
    Deleted,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind", content = "value")]
pub enum Kerning {
    #[default]
    Metrics,
    Optical,
    /// Zero ("0" in the kerning menu).
    None,
    /// Manual pair kerning in 1/1000 em (applies after this character).
    Manual(f64),
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Capitalization {
    #[default]
    Normal,
    AllCaps,
    SmallCaps,
    OpenTypeAllSmallCaps,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Position {
    #[default]
    Normal,
    Superscript,
    Subscript,
    OtSuperscript,
    OtSubscript,
    OtNumerator,
    OtDenominator,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Align {
    #[default]
    Left,
    Center,
    Right,
    LeftJustified,
    CenterJustified,
    RightJustified,
    FullyJustified,
    TowardsSpine,
    AwayFromSpine,
}

impl Align {
    pub fn is_justified(self) -> bool {
        matches!(self, Align::LeftJustified | Align::CenterJustified | Align::RightJustified | Align::FullyJustified)
    }
    pub const ALL: [Align; 9] = [
        Align::Left,
        Align::Center,
        Align::Right,
        Align::LeftJustified,
        Align::CenterJustified,
        Align::RightJustified,
        Align::FullyJustified,
        Align::TowardsSpine,
        Align::AwayFromSpine,
    ];
    pub fn label(self) -> &'static str {
        match self {
            Align::Left => "Align left",
            Align::Center => "Align center",
            Align::Right => "Align right",
            Align::LeftJustified => "Justify with last line aligned left",
            Align::CenterJustified => "Justify with last line aligned center",
            Align::RightJustified => "Justify with last line aligned right",
            Align::FullyJustified => "Justify all lines",
            Align::TowardsSpine => "Align towards spine",
            Align::AwayFromSpine => "Align away from spine",
        }
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Composer {
    /// Total-fit (Knuth–Plass) over the whole paragraph.
    #[default]
    Paragraph,
    /// Greedy, line by line.
    SingleLine,
}

/// What a nested style runs to (Drop Caps and Nested Styles).
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind", content = "chars")]
pub enum NestedUntil {
    Sentences,
    #[default]
    Words,
    Characters,
    Letters,
    Digits,
    Tab,
    ForcedLineBreak,
    EmSpace,
    EnSpace,
    /// Any of these characters.
    Chars(String),
}

/// A character style applied from the start of the paragraph through (or up to) the `count`-th
/// delimiter; nested styles follow each other.
/// A nested line style: `style` for the next `lines` lines.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct NestedLineStyle {
    pub style: String,
    pub lines: u32,
}

impl Default for NestedLineStyle {
    fn default() -> Self {
        NestedLineStyle { style: String::new(), lines: 1 }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct NestedStyle {
    pub style: String,
    /// Through (include the delimiter) or up to (stop before it).
    pub through: bool,
    pub count: u32,
    pub until: NestedUntil,
}

impl Default for NestedStyle {
    fn default() -> Self {
        NestedStyle { style: String::new(), through: true, count: 1, until: NestedUntil::Words }
    }
}

/// A character style applied to every match of a regular expression in the paragraph.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct GrepStyle {
    pub style: String,
    pub pattern: String,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum GridAlign {
    #[default]
    None,
    AllLines,
    FirstLineOnly,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum StartParagraph {
    #[default]
    Anywhere,
    NextColumn,
    NextFrame,
    NextPage,
    NextOddPage,
    NextEvenPage,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind", content = "columns")]
pub enum SpanColumns {
    #[default]
    Single,
    /// Span `n` columns (0 = all).
    Span(u32),
    /// Split into `n` sub-columns.
    Split(u32),
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TabAlign {
    #[default]
    Left,
    Center,
    Right,
    /// Align on a character (default `.`).
    Char,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TabStop {
    pub position: f64,
    #[serde(default)]
    pub align: TabAlign,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub leader: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub align_on: String,
}

/// A paragraph rule (Rule Above / Rule Below).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct Rule {
    pub on: bool,
    pub weight: f64,
    pub color: String,
    pub tint: f32,
    /// Width: column (true) or text (false).
    pub column_width: bool,
    pub offset: f64,
    pub left_indent: f64,
    pub right_indent: f64,
}

impl Default for Rule {
    fn default() -> Self {
        Rule { on: false, weight: 1.0, color: "[Black]".into(), tint: 1.0, column_width: true, offset: 0.0, left_indent: 0.0, right_indent: 0.0 }
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ListType {
    #[default]
    None,
    Bullets,
    Numbers,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum NumberStyle {
    #[default]
    Arabic,
    UpperRoman,
    LowerRoman,
    UpperLetters,
    LowerLetters,
    /// 01, 02, …
    ArabicLeadingZero,
    /// *, †, ‡, §, ¶, ‖, then doubled (**, ††, …): footnotes.
    Symbols,
}

impl NumberStyle {
    pub fn format(self, n: u32) -> String {
        match self {
            NumberStyle::Arabic => n.to_string(),
            NumberStyle::ArabicLeadingZero => format!("{n:02}"),
            NumberStyle::UpperRoman => roman(n),
            NumberStyle::LowerRoman => roman(n).to_lowercase(),
            NumberStyle::UpperLetters => letters(n),
            NumberStyle::LowerLetters => letters(n).to_lowercase(),
            NumberStyle::Symbols => {
                const SYM: [char; 6] = ['*', '†', '‡', '§', '¶', '‖'];
                let n = n.max(1) as usize - 1;
                std::iter::repeat_n(SYM[n % SYM.len()], n / SYM.len() + 1).collect()
            }
        }
    }
}

fn roman(mut n: u32) -> String {
    if n == 0 {
        return "0".into();
    }
    let t = [
        (1000, "M"),
        (900, "CM"),
        (500, "D"),
        (400, "CD"),
        (100, "C"),
        (90, "XC"),
        (50, "L"),
        (40, "XL"),
        (10, "X"),
        (9, "IX"),
        (5, "V"),
        (4, "IV"),
        (1, "I"),
    ];
    let mut s = String::new();
    for (v, r) in t {
        while n >= v {
            s.push_str(r);
            n -= v;
        }
    }
    s
}

/// A, B, …, Z, AA, BB, … (InDesign's letter numbering repeats the letter).
fn letters(n: u32) -> String {
    if n == 0 {
        return String::new();
    }
    let i = (n - 1) % 26;
    let reps = (n - 1) / 26 + 1;
    std::iter::repeat_n(char::from(b'A' + i as u8), reps as usize).collect()
}

attr_set! {
    /// Character attributes (Character panel / character styles / the character part of paragraph styles).
    CharAttrs / CharProps {
        font_family: String = "Source Serif 4".into(),
        font_style: String = "Regular".into(),
        /// Point size.
        size: f64 = 12.0,
        leading: Leading = Leading::Auto,
        kerning: Kerning = Kerning::Metrics,
        /// Tracking in 1/1000 em.
        tracking: f64 = 0.0,
        /// Explicit CJK aki, in em; None restores automatic spacing.
        leading_aki: Option<f64> = None,
        trailing_aki: Option<f64> = None,
        /// Proportional character compression, 0..1.
        tsume: f64 = 0.0,
        /// Target em cells for the contiguous formatted group (0 disables jidori).
        jidori: u32 = 0,
        character_alignment: crate::cjk::CharacterAlignment = crate::cjk::CharacterAlignment::Baseline,
        leading_model: crate::cjk::LeadingModel = crate::cjk::LeadingModel::Roman,
        /// Explicit emphasis character; empty uses the traditional sesame dot.
        kenten_character: String = String::new(),
        /// Horizontal / vertical scale, 1.0 = 100%.
        h_scale: f64 = 1.0,
        v_scale: f64 = 1.0,
        baseline_shift: f64 = 0.0,
        /// Skew (false italic), degrees.
        skew: f64 = 0.0,
        fill: String = "[Black]".into(),
        fill_tint: f32 = 1.0,
        stroke: String = "[None]".into(),
        stroke_tint: f32 = 1.0,
        stroke_weight: f64 = 1.0,
        capitalization: Capitalization = Capitalization::Normal,
        position: Position = Position::Normal,
        underline: bool = false,
        strikethrough: bool = false,
        /// Underline Options: weight and offset below the baseline (`None` = from the size),
        /// colour (empty = the text colour) and tint.
        underline_weight: Option<f64> = None,
        underline_offset: Option<f64> = None,
        underline_color: String = String::new(),
        underline_tint: f32 = 1.0,
        /// Strikethrough Options: offset above the baseline.
        strikethrough_weight: Option<f64> = None,
        strikethrough_offset: Option<f64> = None,
        strikethrough_color: String = String::new(),
        strikethrough_tint: f32 = 1.0,
        glyph_form: String = String::new(),
        ligatures: bool = true,
        no_break: bool = false,
        /// Tate-chu-yoko: in vertical text, the run is set horizontally within one em of the line.
        tate_chu_yoko: bool = false,
        tate_chu_yoko_x_offset: f64 = 0.0,
        tate_chu_yoko_y_offset: f64 = 0.0,
        /// Ruby: the reading set small above the text (to its right in vertical text), one group
        /// over each run that has it.
        ruby: String = String::new(),
        /// Kenten: an emphasis dot above each character.
        kenten: bool = false,
        /// Digits (World-Ready): how 0–9 are drawn.
        digits: Digits = Digits::Default,
        character_direction: crate::arabic::CharacterDirection = crate::arabic::CharacterDirection::Default,
        /// Character-level permission, additionally gated by paragraph kashidas.
        allow_kashidas: bool = true,
        diacritic_position: crate::arabic::DiacriticPosition = crate::arabic::DiacriticPosition::Default,
        /// Additional mark offsets, in thousandths of an em. Positive y is up.
        diacritic_x_offset: f64 = 0.0,
        diacritic_y_offset: f64 = 0.0,
        /// IDML contextual-form request, separate from general OpenType features.
        positional_form: String = String::new(),
        language: String = "English: USA".into(),
        /// Additional OpenType features, e.g. `["onum", "ss01"]`.
        otf_features: Vec<String> = Vec::new(),
        /// Conditional text: the conditions applied (Window › Type & Tables › Conditional Text).
        conditions: Vec<String> = Vec::new(),
        /// Track Changes: text added or deleted while tracking (deleted text isn't laid out).
        change: ChangeMark = ChangeMark::None,
        /// XML: the element this text is tagged with (Tags panel, inline).
        xml_tag: String = String::new(),
    }
}

attr_set! {
    /// Paragraph attributes (Paragraph panel / paragraph styles).
    ParaAttrs / ParaProps {
        align: Align = Align::Left,
        /// Paragraph Direction (World-Ready): the base direction lines are ordered in.
        direction: TextDirection = TextDirection::LeftToRight,
        left_indent: f64 = 0.0,
        right_indent: f64 = 0.0,
        first_line_indent: f64 = 0.0,
        last_line_indent: f64 = 0.0,
        space_before: f64 = 0.0,
        space_after: f64 = 0.0,
        drop_cap_lines: u32 = 0,
        drop_cap_chars: u32 = 0,
        /// Nested styles, in order from the paragraph start.
        nested_styles: Vec<NestedStyle> = Vec::new(),
        /// GREP styles: a character style for every match of a pattern (applied after nested).
        grep_styles: Vec<GrepStyle> = Vec::new(),
        /// Nested line styles: a character style for the paragraph's first lines, in order.
        nested_line_styles: Vec<NestedLineStyle> = Vec::new(),
        grid_align: GridAlign = GridAlign::None,
        composer: Composer = Composer::Paragraph,
        // Hyphenation
        hyphenate: bool = true,
        hyph_min_word: u32 = 5,
        hyph_after_first: u32 = 2,
        hyph_before_last: u32 = 2,
        /// Max consecutive hyphenated lines (0 = unlimited).
        hyph_limit: u32 = 3,
        hyph_zone: f64 = 36.0,
        hyph_capitalized: bool = true,
        hyph_last_word: bool = true,
        hyph_across_column: bool = true,
        /// Better spacing (0) ↔ fewer hyphens (1).
        hyph_weight: f64 = 0.5,
        // Justification (percent as fractions)
        word_space_min: f64 = 0.8,
        word_space_desired: f64 = 1.0,
        word_space_max: f64 = 1.33,
        letter_space_min: f64 = 0.0,
        letter_space_desired: f64 = 0.0,
        letter_space_max: f64 = 0.0,
        glyph_scale_min: f64 = 1.0,
        glyph_scale_desired: f64 = 1.0,
        glyph_scale_max: f64 = 1.0,
        auto_leading: f64 = 1.2,
        single_word_justify: Align = Align::FullyJustified,
        /// Insert Kashidas (World-Ready): justified Arabic lines stretch at joins before spaces.
        kashidas: bool = true,
        /// Preserved vendor policy; non-default policies require a dedicated composer.
        arabic_justification: String = String::new(),
        paragraph_kashida_width: Option<f64> = None,
        // Keeps
        keep_with_next: u32 = 0,
        keep_lines_together: bool = false,
        keep_all_lines: bool = true,
        keep_first: u32 = 2,
        keep_last: u32 = 2,
        start_paragraph: StartParagraph = StartParagraph::Anywhere,
        span_columns: SpanColumns = SpanColumns::Single,
        rule_above: Rule = Rule::default(),
        rule_below: Rule = Rule::default(),
        tabs: Vec<TabStop> = Vec::new(),
        list_type: ListType = ListType::None,
        /// Named list (Define Lists) the numbers belong to ("" = the story's own list).
        list_name: String = String::new(),
        /// Start At: restart the numbering at this number.
        start_at: Option<u32> = None,
        bullet_char: String = "\u{2022}".into(),
        number_style: NumberStyle = NumberStyle::Arabic,
        /// Text after the number/bullet (`^t` = tab).
        list_separator: String = "\t".into(),
        balance_ragged: bool = false,
        optical_margin: bool = false,
        /// None uses the legacy built-in rules; an empty set explicitly disables kinsoku.
        kinsoku: Option<crate::cjk::Kinsoku> = None,
        /// Preserved spacing-table reference; compatibility audit reports unsupported composition.
        mojikumi: String = String::new(),
        /// Preserved priority policy; the current breaker does not implement these priorities.
        kinsoku_type: String = String::new(),
        kinsoku_hang: crate::cjk::KinsokuHang = crate::cjk::KinsokuHang::None,
        bunri_kinshi: bool = false,
        rensuuji: bool = true,
        treat_ideographic_space_as_space: bool = false,
        /// Paragraph shading, and how far it reaches past the text: top, left, bottom, right.
        shading_on: bool = false,
        shading_color: String = "[Black]".into(),
        shading_tint: f32 = 0.2,
        shading_offsets: [f64; 4] = [0.0; 4],
        /// Paragraph border: stroke weights (top, left, bottom, right), colour, and offsets past the
        /// text (top, left, bottom, right).
        border_on: bool = false,
        border_weights: [f64; 4] = [1.0; 4],
        border_color: String = "[Black]".into(),
        border_tint: f32 = 1.0,
        border_offsets: [f64; 4] = [0.0; 4],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn digits_map_to_their_script() {
        assert_eq!(Digits::Default.map('7', "Arabic"), '7');
        assert_eq!(Digits::Hindi.map('3', ""), '\u{0663}');
        assert_eq!(Digits::Farsi.map('0', ""), '\u{06F0}');
        assert_eq!(Digits::Native.map('5', "Thai"), '\u{0E55}');
        assert_eq!(Digits::Native.map('5', "English: USA"), '5');
        assert_eq!(Digits::Hindi.map('x', ""), 'x');
    }

    #[test]
    fn merge_and_resolve() {
        let mut a = CharAttrs { size: Some(10.0), ..Default::default() };
        a.merge(&CharAttrs { tracking: Some(20.0), size: Some(11.0), ..Default::default() });
        assert_eq!(a.size, Some(11.0));
        assert_eq!(a.count(), 2);
        let mut p = CharProps::default();
        p.apply(&a);
        assert_eq!(p.size, 11.0);
        assert_eq!(p.tracking, 20.0);
        assert_eq!(p.font_family, "Source Serif 4");
    }

    #[test]
    fn set_json_by_name() {
        let mut a = ParaAttrs::default();
        a.set_json("spaceBefore", &serde_json::json!(6.0)).unwrap();
        a.set_json("align", &serde_json::json!("center")).unwrap();
        a.set_json("left_indent", &serde_json::json!(12)).unwrap();
        assert_eq!(a.space_before, Some(6.0));
        assert_eq!(a.align, Some(Align::Center));
        assert_eq!(a.left_indent, Some(12.0));
        assert!(a.set_json("nope", &serde_json::json!(1)).is_err());
        a.set_json("align", &serde_json::Value::Null).unwrap();
        assert_eq!(a.align, None);
    }

    #[test]
    fn delta_and_common() {
        let a = CharProps::default();
        let mut b = a.clone();
        b.size = 18.0;
        let d = a.delta(&b);
        assert_eq!(d.count(), 1);
        let c = CharProps::common([&a, &b]);
        assert_eq!(c.size, None);
        assert_eq!(c.font_family.as_deref(), Some("Source Serif 4"));
    }

    #[test]
    fn serde_skips_unset() {
        let a = CharAttrs { size: Some(9.0), ..Default::default() };
        assert_eq!(serde_json::to_string(&a).unwrap(), r#"{"size":9.0}"#);
        let p: ParaProps = serde_json::from_str(r#"{"align":"center"}"#).unwrap();
        assert_eq!(p.align, Align::Center);
        assert_eq!(p.word_space_max, 1.33);
    }

    #[test]
    fn numbering_styles() {
        assert_eq!(NumberStyle::UpperRoman.format(14), "XIV");
        assert_eq!(NumberStyle::LowerRoman.format(9), "ix");
        assert_eq!(NumberStyle::UpperLetters.format(1), "A");
        assert_eq!(NumberStyle::UpperLetters.format(27), "AA");
        assert_eq!(NumberStyle::LowerLetters.format(28), "bb");
        assert_eq!(NumberStyle::ArabicLeadingZero.format(3), "03");
    }
}
